services:
  - type: web
    name: hopeful-ribbon-website
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn App.app:app
    envVars:
      - key: SECRET_KEY
        value: your_secret_key
      - key: EMAIL_USER
        value: your_email
      - key: EMAIL_PASSWORD
        value: your_email_password
